support for cross-submission, cpu_type, random start delay

diff --git a/bin/launch_cf b/bin/launch_cf
--- a/bin/launch_cf
+++ b/bin/launch_cf
@@ -65,10 +65,74 @@ Examples:
 EOF
 }
 
+
+#------------------------------------------------------------------
+set_defaults ()
+{
+    case "${1}" in
+        "derecho")
+            max_ppn=128
+            [ -z "${ppn}" ]       && ppn=${max_ppn}
+            [ -z "${mem_limit}" ] && mem_limit="235G"
+            [ -z "${queue}" ]     && queue="main"
+            ;;
+        "casper")
+            max_ppn=36
+            # use less than full nodes on Casper by default
+            [ -z "${ppn}" ]       && ppn=1
+            [ -z "${mem_limit}" ] && mem_limit="10G"
+            [ -z "${queue}" ]     && queue="casper"
+            ;;
+        *)
+            echo "ERROR: Unrecognized execution host=${1}"
+            exit 1
+    esac
+    return
+}
+
+
+#------------------------------------------------------------------
+parse_queue_args ()
+{
+    while [ ${#} -gt 0 ] ; do
+        case ${1} in
+            "-q"|"--queue")
+                shift
+                queue=${1}
+                shift
+                case ${queue} in
+                    *"@casper-pbs"*) execution_host="casper";   ;;
+                    *"@desched"*)    execution_host="derecho";  ;;
+                esac
+                ;;
+            # ignore anything else (will get to those in the comprehensive parse_args
+            *)
+                shift
+                ;;
+        esac
+    done
+    return
+}
+
 #------------------------------------------------------------------
 parse_args ()
 {
+    # var defaults.
+    execution_host="${NCAR_HOST}"
+    command_file="./cmdfile"
+    threads_per_step=1
+    max_start_delay=0
+    unset ppn
+    unset steps_per_node
+    unset cpu_type
+    unset mem_limit
+    unset queue
     unset args_for_pbs
+
+    # if the user specifies -q|--queue, and the target requires cross-submission, that will
+    # influence our defaults.
+    parse_queue_args ${@}
+    set_defaults ${execution_host}
 
     while [ ${#} -gt 0 ] ; do
         # check the first argument
@@ -113,7 +177,7 @@ parse_args ()
 
             "--mem"|"--memory")
                 shift
-                memlimit=${1}
+                mem_limit=${1}
                 shift
                 ;;
 
@@ -140,42 +204,19 @@ parse_args ()
         esac
     done
 
+    # Consistency
+    [ ${threads_per_step} -gt ${ppn} ] && ppn=${threads_per_step}
+    [ -z "${steps_per_node}" ] && steps_per_node=$(( ${ppn} / ${threads_per_step} ))
+    [ $(( ${steps_per_node}*${threads_per_step})) -gt ${max_ppn} ] && { echo "steps_per_node*threads_per_step>${max_ppn}, inconsistent inputs?!"; usage; exit 1; }
+    [ $(( ${steps_per_node}*${threads_per_step})) -gt ${ppn} ] && ppn=$(( ${steps_per_node}*${threads_per_step}))
+
+    [ ${ppn} -gt ${max_ppn} ] && { echo "ppn>${max_ppn}m inconsistent inputs?!"; usage; exit 1; }
+
     return
 }
 
 #------------------------------------------------------------------
-# var defaults.
-command_file="./cmdfile"
-threads_per_step=1
-max_start_delay=0
-unset cpu_type
-
-case "${NCAR_HOST}" in
-    "derecho")
-        ppn=128
-        memlimit="235G"
-        queue="main"
-        ;;
-    "casper")
-        # use less than full nodes on Casper.
-        ppn=1
-        memlimit="10G"
-        queue="casper"
-        ;;
-    "cheyenne")
-        ppn=36
-        memlimit="50G"
-        queue="regular"
-        ;;
-    *)
-        echo "ERROR: Unrecognized NCAR_HOST=${NCAR_HOST}"
-        exit 1
-esac
-
-# more defaults that depend on case above
-steps_per_node=${ppn}
-
-# finally, allow the user specify options
+# defaults & user arguments
 parse_args ${@}
 
 #------------------------------------------------------------------
@@ -192,23 +233,27 @@ echo "Found n_total_steps=${n_total_steps} in ${command_file}"
 [ ${n_total_steps} -lt ${steps_per_node} ] && steps_per_node=${n_total_steps}
 [ ${n_total_steps} -lt ${ppn} ]            && ppn=${n_total_steps}
 
-
-
 #------------------------------------------------------------------
 njobs=$(( ${n_total_steps} / ${steps_per_node} ))
 # evenly divisible?
 [ $(( ${njobs} * ${steps_per_node} )) -eq ${n_total_steps} ] && njobs=$((${njobs}-1))
-echo "Running $((${njobs}+1)) jobs with ${steps_per_node} steps / node on NCAR resource ${NCAR_HOST}"
 
+echo " -> ppn=${ppn}"
+echo " -> threads_per_step=${threads_per_step}"
+echo " -> steps_per_node=${steps_per_node}"
+echo " -> n_total_steps=${n_total_steps}"
+echo " -> njobs=${njobs}"
+
+echo "Running $((${njobs}+1)) jobs with ${steps_per_node} steps / node on NCAR resource ${execution_host}"
 
 # hackery: PBS will not allow us to submit a 1-entry array.
 # for that case we will be submitted without a -J arg
 [ ${njobs} -gt 0 ] && args_for_pbs="-J 0-${njobs} ${args_for_pbs}"
 
-ss="1:ncpus=${ppn}:mpiprocs=${steps_per_node}:ompthreads=${threads_per_step}:mem=${memlimit}"
+ss="1:ncpus=${ppn}:mpiprocs=${steps_per_node}:ompthreads=${threads_per_step}:mem=${mem_limit}"
 
 # append cpu_type to select statement, if set.
-[ -z "${cpu_type+x}" ] && echo "no cpu_type specified" || args_for_pbs="-l cpu_type=${cpu_type} ${args_for_pbs}"
+[ -z "${cpu_type+x}" ] || args_for_pbs="-l cpu_type=${cpu_type} ${args_for_pbs}"
 
 set -x
 qsub -v command_file="${command_file}",max_start_delay="${max_start_delay}" \
