Updates to scripts

diff --git a/qcmd b/qcmd
--- a/qcmd
+++ b/qcmd
@@ -16,12 +16,12 @@ handle_logs () {
         fi
     fi
     
-    rm -f $QCMD_SCRIPT $QCMD_IDFILE
+    rm $QCMD_SCRIPT $QCMD_IDFILE
 }
 
 check_job () {
     if ! kill -0 $QCMD_SPID >& /dev/null; then
-        echo "Error: PBS could not successfully start job. Exiting..."
+        >&2 echo "Error: PBS could not successfully start job. Exiting..."
         exit 1
     fi
 
@@ -29,13 +29,24 @@ check_job () {
 }
 
 clean_up () {
-    sleep 5
-    if [[ ! -z $QCMD_JOB ]]; then
-        echo -e "\nqcmd job $QCMD_JOB terminated"
+    if [[ -n $QCMD_SPID ]]; then
+        kill $QCMD_SPID
+        >&2 echo "qcmd job terminated $QCMD_JOB"
         handle_logs "Job terminated before completion"
+    else
+        rm -f $QCMD_SCRIPT $QCMD_IDFILE $QCMD_PROCFILE
     fi
-    exit 2
+
+    exit 1
 }
+
+# Throttle and then check for too many on node
+QCMD_ALLOW=$(pgrep -u $USER qcmd | xargs ps --no-headers -o pid --sort=etime -p | head -n 5 | xargs)
+
+if [[ " $QCMD_ALLOW " != *" $$ "* ]]; then
+    >&2 echo "Error: already at max qcmd job count (5)"
+    exit 1
+fi
 
 trap clean_up SIGHUP SIGINT SIGQUIT SIGTERM
 
@@ -94,7 +105,7 @@ for n in $PBSOPT; do
             fi
             ;;
         -e*)
-            echo "Note: separate output and error log files are not supported by qcmd"
+            >&2 echo "Note: separate output and error log files are not supported by qcmd"
             ;;
         *)
             case $READVAL in
@@ -111,7 +122,7 @@ for n in $PBSOPT; do
 done
 
 if [[ $ARGV != *"-- "* ]]; then
-    echo "Error: no command specified!"
+    >&2 echo "Error: no command specified!"
     usage 1
 fi
 
@@ -159,7 +170,7 @@ $EXECMD
 EOF
 
 # Submit job in background and then get job ID
-qsub $PBSARGS -j oe -k oed -o $QCMD_LOG -W block=true -N qcmd $QCMD_SCRIPT > $QCMD_IDFILE &
+qsub $PBSARGS -V -j oe -k oed -o $QCMD_LOG -W block=true -N qcmd $QCMD_SCRIPT > $QCMD_IDFILE &
 QCMD_SPID=$!
 
 while [[ ! -s $QCMD_IDFILE ]]; do
@@ -171,8 +182,8 @@ QCMD_JOB=$(cat $QCMD_IDFILE)
 # Check that job ID was produced
 if [[ ! $QCMD_JOB =~ ^[0-9]+.* ]]; then
     echo $QCMD_JOB
-    echo "Error: error in qsub submission. Exiting ..."
-    exit 1
+    >&2 echo "Error: error in qsub submission. Exiting ..."
+    clean_up
 fi
 
 echo -e "Waiting for job $QCMD_JOB to start ... \n\n"
diff --git a/qinteractive b/qinteractive
--- a/qinteractive
+++ b/qinteractive
@@ -1,77 +1,211 @@
-#!/bin/bash
+#!/bin/bash 
 
-# Here are the default settings at the moment
-NODES=1
-CPUS=1
-MPIPROCS=1
-QUEUE=share
-WALLTIME=3600
+NCHUNKS= NCPUS= NTASKS= NTHREADS=
+QSUBCMD=qsub SKIPQSUB=false
+DEFOPTS=" -l -q -A "
+DEFRES='-l select=${NCHUNKS:-1}:ncpus=${NCPUS:-1}:mpiprocs=${NTASKS:-1}'
+
+declare -A PBSOPTS RESFLAGS
+RESFLAGS=( [NTHREADS]=ompthreads [MEM]=mem [CPU]=cpu_type [NGPUS]=ngpus )
+
+# Default settings based on the current system
+if [[ $0 == *qinteractive* ]]; then
+    QUEUE=share
+    WALLTIME=3600
+    ACVAR=PBS_ACCOUNT
+    SERVERNAME=chadmin1.ib0.cheyenne.ucar.edu
+else
+    if [[ $@ == *-q*( )gpudev* ]]; then
+        QUEUE=gpudev
+        WALLTIME=00:30:00
+        DEFRES=${DEFRES}':ngpus=${NGPUS:-1}'
+        PBSOPTS[GPUTYPE]="-l gpu_type=v100"
+    else
+        QUEUE=casper
+        WALLTIME=06:00:00
+    fi
+
+    ACVAR=DAV_PROJECT
+    SERVERNAME=casper-pbs
+fi
+
+PBSOPTS[WALLTIME]="-l walltime=${WALLTIME}"
+PBSOPTS[QUEUE]="-q ${QUEUE}@${SERVERNAME}"
 
 usage () {
 cat << EOF
-Usage: qinteractive [PBS options] 
+Usage: $(basename $0) [PBS options] 
 
-This command will start an interactive job on the share queue using one core
+This command will start an interactive job on the $QUEUE queue using one core
 by default. Any arguments submitted to the script will be forwarded to the qsub
-command, enabling you to override script defaults (e.g., walltime).
+command, enabling you to override script defaults (e.g., walltime). In addition
+to the standard PBS options, this command provides the following short resource
+flags:
 
-You have three ways of selecting an account to use for the submission:
+    --nchunks       [CHUNK COUNT]
+    --ntasks        [MPI TASKS PER CHUNK]
+    --nthreads      [SMP THREADS PER CHUNK]
+    --mem           [MEMORY PER CHUNK]
+EOF
+
+if [[ $QUEUE == casper ]]; then
+    echo "    --ngpus         [GPUS PER CHUNK]"
+    echo "    --cpu           [CPU TYPE]"
+    echo "    --gpu           [GPU TYPE]"
+fi
+
+cat << EOF
+
+Note that heteorogenous resource requests are not possible using the short-form
+options. Use a standard "-l select=" flag for heteorogenous jobs.
+
+You have two ways of selecting an account to use for the submission:
 
 1. Use the PBS -A [account] command line argument
-2. Set the PBS_ACCOUNT environment variable
-3. Let qinteractive randomly select from your active project list
+2. Set the $ACVAR environment variable
 
-Current PBS_ACCOUNT value = $PBS_ACCOUNT
+If you do not set an account to use, a random project will be chosen from the 
+list of valid projects for your username. It is best to set an account!
+
+Current $ACVAR value = ${!ACVAR}
 EOF
 exit
 }
 
-PBSOPT="$@"
+function get_value {
+    ARGFLAG=$(cut -d= -f1 <<< ${1^^} | tr -d '-')
+    
+    if [[ $1 == *=* ]]; then
+        declare -g $ARGFLAG=${1#*=}
+    fi
+}
 
 # Parse command line arguments
-for n in $PBSOPT; do
-	case $n in
-		--help)
-			usage
-			;;
-		-A*)
-			if [[ $n == -A ]]; then
-				READVAL=account
-			else
-				JOB_ACCOUNT=${n/-A/}
-			fi
-			;;
-		*)
-			if [[ $READVAL == account ]]; then
-				JOB_ACCOUNT=$n
-				READVAL=
-			fi
-			;;
-	esac
+while [[ $# -gt 0 ]]; do
+    ARG=$1
+
+    case $ARG in
+        --help)
+    	    usage
+            ;;
+        --show)
+            SKIPQSUB=true
+            ;;
+        --[a-z]*)
+            get_value $ARG
+            ;;
+        *)
+            ARGOPT=${ARG:0:2} ARGFLAG=
+            
+            if [[ $DEFOPTS == *" $ARGOPT "* ]]; then
+                ARGVAL=${ARG:2}
+
+                if [[ -z $ARGVAL ]]; then
+                    shift; ARG=$1
+
+                    if [[ $ARG == -* ]]; then
+                        >&2 echo "Error: invalid input for option $ARGOPT: $ARG"
+                        exit 1
+                    else
+                        ARGVAL=$ARG
+                    fi
+                fi
+                
+                if [[ $ARGOPT == -l ]]; then
+                    if [[ $ARGVAL == select* ]]; then
+                        PBSOPTS[SELECT]="-l $ARGVAL"
+                    elif [[ $ARGVAL == walltime* ]]; then
+                        PBSOPTS[WALLTIME]="-l $ARGVAL"
+                    else
+                        PBSARGS="$PBSARGS -l $ARGVAL"
+                    fi
+                elif [[ $ARGOPT == -q ]]; then
+                    if [[ $ARGVAL != *@* ]]; then
+                        PBSOPTS[QUEUE]="-q ${ARGVAL}@$SERVERNAME"
+                    else
+                        PBSOPTS[QUEUE]="-q $ARGVAL"
+                    fi
+                elif [[ $ARGOPT == -A ]]; then
+                    PBSOPTS[ACCOUNT]="-A $ARGVAL"
+                fi
+            else
+                PBSARGS="$PBSARGS $ARG"
+            fi
+            ;;
+    esac
+   
+    if [[ -n $ARGFLAG ]]; then
+        if [[ -z ${!ARGFLAG} ]]; then
+            declare $ARGFLAG=$2
+            shift
+        fi
+
+        case $ARGFLAG in
+            NTHREADS|MEM|NGPUS|CPU)
+                if [[ $DEFRES != *":${RESFLAGS[$ARGFLAG]}="* ]]; then
+                    DEFRES=$DEFRES":${RESFLAGS[$ARGFLAG]}=\$${ARGFLAG}"
+                fi
+                ;;
+            GPU)
+                PBSOPTS[GPUTYPE]="-l gpu_type=$GPU"
+                ;;
+        esac
+    fi
+
+    shift
 done
 
-# If JOB_ACCOUNT is still not set, then use defaults
-if [[ -z $JOB_ACCOUNT ]]; then
-	if [[ -z $PBS_ACCOUNT ]]; then
-		JOB_ACCOUNT=$(/ncar/opt/sam/sam_validate.py $USER | grep -m1 True | cut -d ',' -f 1)
-	else
-		JOB_ACCOUNT=$PBS_ACCOUNT
-	fi
+if [[ " ${!PBSOPTS[@]} " != *" ACCOUNT "* ]]; then
+    if [[ -n ${!ACVAR} ]]; then
+        JOB_ACCOUNT=${!ACVAR}
+    else
+        JOB_ACCOUNT=$(/ncar/opt/sam/sam_validate.py $USER 2> /dev/null | grep -m1 True | cut -d ',' -f 1; exit ${PIPESTATUS[0]})
 
-	PBSARGS="-A $JOB_ACCOUNT"
+        if [[ $? != 0 ]]; then
+            >&2 echo "Error: cannot query default project - please specify using \$DAV_PROJECT or -A option"
+            exit 1
+        fi
+    fi
+
+    PBSOPTS[ACCOUNT]="-A $JOB_ACCOUNT"
 fi
 
-# Create default list of arguments
-PBSARGS="-I -l select=${NODES}:ncpus=${CPUS}:mpiprocs=${MPIPROCS}	\
-			-l walltime=${WALLTIME} -q ${QUEUE} ${PBSARGS}"
+if [[ -z $NCPUS ]]; then
+    if [[ -n $NTHREADS ]]; then
+        NCPUS=$((NTASKS * NTHREADS))
+    else
+        NCPUS=$NTASKS
+    fi
+fi
 
-echo -e "Submitting interactive job to PBS using account $JOB_ACCOUNT ...\n"
+if [[ $NCPUS -gt 36 ]]; then
+    NCPUS=36
+fi
 
-if [[ ! -z $PBSOPT ]]; then
-	echo -e "Requested custom PBS options:\n    $PBSOPT\n"
+# Substitute values into default select
+if [[ -z ${PBSOPTS[SELECT]} ]]; then
+    eval PBSOPTS[SELECT]=\"$DEFRES\"
+fi
 
-	PBSARGS="$PBSARGS $PBSOPT"
+# Submit job using collected parameters
+echo -e "Submitting interactive job to PBS ..."
+
+if [[ -n $DISPLAY ]]; then
+    # Test display to avoid qsub error
+    if [[ -n "$(xauth list $DISPLAY)" ]]; then
+        PBSARGS="-X $PBSARGS"
+        echo -e "Setting display for X forwarding ...\n"
+    else
+        echo -e "Display not available; X forwarding disabled ...\n"
+    fi
+else
+    echo -e "No display; X forwarding disabled ...\n"
 fi
 
 # Submit job request and put any user requests second to override defaults
-qsub $PBSARGS
+echo "Running command:"
+echo -e "$QSUBCMD -I $PBSARGS ${PBSOPTS[@]}\n"
+
+if [[ $SKIPQSUB == false ]]; then
+    $QSUBCMD -I $PBSARGS ${PBSOPTS[@]}
+fi
